#!/bin/sh

GRAY='\033[0;37m'
RED='\033[0;31m'

ru=`cat /etc/passwd | awk -F: {'print $1 " "$3'} | awk {'if ($2 >= 1000 && $2 <= 9999) print $1" "$2'}`
echo ${GRAY}"cat /etc/passwd | awk -F: {'print $1 " "$3'} | awk {'if ($2 >= 1000) print $1" "$2'}"
echo "${RED}$ru"
