#!bin/sh

u=`cat /etc/passwd | awk -F: {'print $1 " "$3'} | awk {'if ($2 >= 1000 && $2 <= 9999) print $1" "$2'}`
p=`echo $u | awk {'print $1'}`
for proc in $(ps U $p | awk {'print $1'} | grep -v "PID"); do kill -9 $proc; done;
userdel -f $p
